### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by lorddaedra** [manchenkoff/openapi3-parser#51]
Please, update dependencies (`openapi-spec-validator`) https://github.com/manchenkoff/openapi3-parser/blob/master/Pipfile#L14

OpenAPI file may contain `required` list of names of properties, which do not exists in `properties` list...   
openapi-spec-validator-0.4.0 -> error
openapi-spec-validator-0.5.5 -> OK

Your tool require < 0.5 version of openapi-spec-validator

P.S. Also IMHO it's a good idea to replace `Pipfile*` to `pyproject.toml` (use `poetry`)

Related issue: https://github.com/getlago/lago-openapi/issues/22

**Comment by manchenkoff** [comment]
Bumped to `openapi-spec-validator-0.5.5`
