### ISSUE TITLE
[BUG] `nullable` enums do not add `null` to the enum list

### ISSUE THREAD

**Issue by Pizzaface** [manchenkoff/openapi3-parser#74]
**Describe the bug**
When adding a `nullable` `enum` Schema, the operation will fail unless `null` is directly provided in the `enum` list. This is because `nullable` is not processed before the schema is validated and not having `null` in the values causes an error.

The error is similar to:
```
openapi_parser.errors.ParserError: OpenAPI validation error: 
("None is not one of ['asc', 'desc']", 'enum', deque([]), None, [], ['asc', 'desc'], None, {'type': 'string', 'nullable': True, 'default': None, 'enum': ['asc', 'desc']}, deque(['enum']), None)
```

**To Reproduce**
1. Create an endpoint with a `nullable` `string` parameter.
2. Do not include `null` in the enum values
3. Attempt to parse the spec

**Expected behavior**
When adding a `nullable` field - the property should have `null` automatically added to the enum list - with the default being `null` if not supplied while allowing a set value.

**System details (please complete the following information):**
 - OS: [Ubuntu]
 - OpenAPI / Swagger version [OpenAPI 3.0.1]
 - Python version [3.10.12]

**Comment by manchenkoff** [comment]
Hey @Pizzaface, this error is coming from `prance` package since I do not have any validation for enums. Could you please check if some newer version works with that? If yes, I could upgrade the dependency, but if not, please open the issue in the related repo - [Prance](https://github.com/RonnyPfannschmidt/prance)

**Comment by Pizzaface** [comment]
Whoops! Sorry about that - appreciate the quick response. Will open an issue there. Cheers!

**Comment by Pizzaface** [comment]
Bug opened on the prance repo for those who find this issue:

[Bug](https://github.com/RonnyPfannschmidt/prance/issues/159)

**Comment by manchenkoff** [comment]
I'm closing this issue for now, feel free to raise a new one once new version of dependency should be used
